webphone/WebPhoneMobile/WebPhoneMobile/Controllers/billsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebPhoneMobile.Models;

namespace WebPhoneMobile.Controllers
{
    [Authorize(Roles = "Admin")]
    public class billsController : Controller
    {
        private WebPhoneMobileEntities db = new WebPhoneMobileEntities();

        // GET: bills
        public ActionResult Index()
        {
            var bill = db.bill.Include(b => b.client);
            return View(bill.ToList());
        }

        // GET: bills/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bill bill = db.bill.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // GET: bills/Create
        public ActionResult Create()
        {
            ViewBag.client_id = new SelectList(db.client, "client_id", "client_name");
            return View();
        }

        // POST: bills/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "bill_id,client_id,date_order,descriptions")] bill bill)
        {
            if (ModelState.IsValid)
            {
                db.bill.Add(bill);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.client_id = new SelectList(db.client, "client_id", "client_name", bill.client_id);
            return View(bill);
        }

        // GET: bills/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bill bill = db.bill.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            ViewBag.client_id = new SelectList(db.client, "client_id", "client_name", bill.client_id);
            return View(bill);
        }

        // POST: bills/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "bill_id,client_id,date_order,descriptions")] bill bill)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bill).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.client_id = new SelectList(db.client, "client_id", "client_name", bill.client_id);
            return View(bill);
        }

        // GET: bills/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            bill bill = db.bill.Find(id);
            if (bill == null)
            {
                return HttpNotFound();
            }
            return View(bill);
        }

        // POST: bills/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            bill bill = db.bill.Find(id);
            db.bill.Remove(bill);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webphone/WebPhoneMobile/WebPhoneMobile/Controllers/clientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebPhoneMobile.Models;

namespace WebPhoneMobile.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class clientsController : Controller
    {   
        private WebPhoneMobileEntities db = new WebPhoneMobileEntities();
        [Authorize(Roles = "Admin")]
        // GET: clients
        public ActionResult Index()
        {
            return View(db.client.ToList());
        }
        [Authorize(Roles = "Admin")]
        // GET: clients/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            client client = db.client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: clients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: clients/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "client_id,client_name,address,phone,email")] client client)
        {
            if (ModelState.IsValid)
            {
                db.client.Add(client);
                db.SaveChanges();
                return RedirectToAction("showToCart", "shoppingcart");
            }

            return View(client);
        }
        [Authorize(Roles = "Admin")]
        // GET: clients/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            client client = db.client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: clients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "client_id,client_name,address,phone,email")] client client)
        {
            if (ModelState.IsValid)
            {
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(client);
        }
        [Authorize(Roles = "Admin")]
        // GET: clients/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            client client = db.client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // POST: clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            client client = db.client.Find(id);
            db.client.Remove(client);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

webphone/WebPhoneMobile/WebPhoneMobile/Controllers/menuController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPhoneMobile.Models;

namespace WebPhoneMobile.Controllers
{
    public class menuController : Controller
    {
        // GET: menu
        public ActionResult Index()
        {
            using (WebPhoneMobileEntities db = new WebPhoneMobileEntities())
            {
                var category = db.category.ToList();
                Hashtable category_name = new Hashtable();
                foreach (var item in category)
                    category_name.Add(item.category_id, item.category_name);
                ViewBag.category_name = category_name;
                return PartialView("Index");
            }
        }
    }
}

webphone/WebPhoneMobile/WebPhoneMobile/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>H195_2005CT0021</title>
    <link rel="shortcut icon" type="image/png" href="~/Images/logo.png"/>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link href="~/Content/styleLayout.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/Content/themify-icons/themify-icons.css" />
</head>

<body>
    <div id="main">
        <div id="header">
            <div id="nav-logo">
                @*<a href="/Home">*@<img src="~/Images/mssv.png"/>@*</a>*@
            </div>
            <div id="nav-mid">
                <ul id="nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })</li>
                    <li>
                        <a href="">
                            Category<i class="nav-arrow-down dti-angle-down"></i>
                        </a>

                        @{Html.RenderAction("Index", "menu");}
                    </li>
                    <li>@Html.ActionLink("Product", "Index", "products", new { area = "" }, new { @class = "nav-link" })</li>
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Client", "Index", "clients", new { area = "" }, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Bill", "Index", "bills")</li>
                    }
                    @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Admin", "Index", "Admin")</li>
                    }
                </ul>
            </div>    
            <div id="nav-login">
                <div class="nav_login">
                    <div class="shopping_cart">
                        <a class="ti-shopping-cart-full" href="@Url.Action("showToCart", "shoppingcart")" style="color: #fff">
                            @Html.Action("BagCart", "shoppingcart")
                        </a>
                    </div>
                    <div class="login">
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </div>            
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    <footer class="page-footer">
        <div class="footer-top">
            <div class="page-main">
                <div class="footer-links-column">
                    <div class="footer-colum-title">
                        <h3>Contact Us</h3>
                    </div>
                    <div class="footer-column-content">
                        <div class="content">
                            <p class="address">
                                <strong><span>Address: </span></strong>
                                <span>52, HM, MLB, CN, TV</span>
                            </p>
                            <p class="email">
                                <strong><span>Mail us: </span></strong>
                                <span><a href="" title="">033hieu033tmh0609@gmail.com</a></span>
                            </p>
                            <p class="phone">
                                <strong><span>Phone: </span></strong>
                                <span>+84 333 210 509</span>
                            </p>
                        </div>
                    </div>
                </div>
                <div class="footer-links-column">
                    <div class="footer-colum-title">
                        <h3>Follow Us</h3>
                    </div>
                    <div class="footer-column-content">
                        <ul class="footer links">
                            <li class="nav item ti-facebook"><a href="#">Facebook</a></li>
                            <li class="nav item ti-instagram"><a href="#">Instagram</a></li>
                            <li class="nav item ti-pinterest-alt"><a href="#">Pinterest</a></li>
                            <li class="nav item ti-twitter-alt"><a href="#">Twitter</a></li>
                            <li class="nav item ti-youtube"><a href="#">Youtube</a></li>
                        </ul>
                    </div>
                </div>
                <div class="footer-links-column">
                    <div class="footer-colum-title">
                        <h3>My Account</h3>
                    </div>
                    <div class="footer-column-content">
                        <ul class="footer links">
                            <li class="nav item ti-arrow-circle-right"><a href="#">My Account</a></li>
                            <li class="nav item ti-arrow-circle-right"><a href="/Account/Login">Login</a></li>
                            <li class="nav item ti-arrow-circle-right"><a href="/shoppingcart/showToCart">My Cart</a></li>
                            <li class="nav item ti-arrow-circle-right"><a href="#">My Compare</a></li>
                            <li class="nav item ti-arrow-circle-right"><a href="#">My Wishlist</a></li>
                        </ul>
                    </div>
                </div>
                <div class="footer-links-column">
                    <div class="footer-colum-title">
                        <h3>Quick Links</h3>
                    </div>
                    <div class="footer-column-content">
                        <ul class="footer links">
                            <li class="nav item ti-arrow-circle-right"><a href="#">Privacy and Cookie Policy </a></li>
                            <li class="nav item ti-arrow-circle-right"><a href="#">Contact Us </a></li>
                            <li class="nav item ti-arrow-circle-right"><a href="#">Orders and Returns </a></li>
                            <a href="/Home"><img src="~/Images/logo.png" style="height: 94px; background-color: #fff; border-radius: 10px;" /></a>
</ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-bottom">
            <div class="page-main">
                <div class="copuright-outer">
                    <small class="copyright">
                        <span>Copyright 2023 Next. All rights reserved.</span>
                    </small>
                    <span class="payment-icons">
                        <ul>
                            <li><a href="#"><img class="image-responsive middle-block" src="https://demo4techies.com/mage/magetheme108/pub/media/wysiwyg/paymet/americanexpress.png" alt="americanexpress"></a></li>
                            <li><a href="#"><img class="image-responsive middle-block" src="https://demo4techies.com/mage/magetheme108/pub/media/wysiwyg/paymet/discover.png" alt="discover"></a></li>
                            <li><a href="#"><img class="image-responsive middle-block" src="https://demo4techies.com/mage/magetheme108/pub/media/wysiwyg/paymet/maestro.png" alt="maestro"></a></li>
                            <li><a href="#"><img class="image-responsive middle-block" src="https://demo4techies.com/mage/magetheme108/pub/media/wysiwyg/paymet/master.png" alt="master"></a></li>
                            <li><a href="#"><img class="image-responsive middle-block" src="https://demo4techies.com/mage/magetheme108/pub/media/wysiwyg/paymet/visa.png" alt="visa"></a></li>
                        </ul>
                    </span>
                </div>
            </div>
        </div>
        @*<script type="text/javascript" xml="space">
                require(['jquery'], function () {
                    var windowWidth = jQuery(window).width();
                    if (windowWidth < 768) {
                        jQuery('.footer-links-column .footer-column-content').hide();
                        jQuery(document).on('click', '.footer-links-column', function () {
                            jQuery(this).addClass('active-column');
                            jQuery(this).find('.footer-column-content').slideDown();
                        });
                        jQuery(document).on('click', '.footer-column-content', function (e) {
                            e.preventdefault();
                            return false;
                        });
                        jQuery(document).on('click', '.footer-links-column.active-column', function () {
                            jQuery(this).removeClass('active-column');
                            jQuery(this).find('.footer-column-content').slideUp();
                        });
                    }
                });
            </script>*@
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>